name: read_more_text
description: A custom Text with trim modes.
version: 0.0.1
author: Figen Güngör <figengungor1@gmail.com>
homepage: https://github.com/figengungor/read_more_text

environment:
  sdk: '>=1.20.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
